### ISSUE TITLE
Can't round-trip XHTML through xmlm

### ISSUE THREAD

**Issue by yminsky** [dbuenzli/xmlm#14]
I'm trying to use xmlm to do transformation some xhtml-like input, and I'm running into an issue. In particular, it doesn't seem possible to handle xhtml entities on both input and output. You can demonstrate this by running xmltrip on some XHTML that contains, say, &nbsp;.  Here's what you get:

    $ echo '<body>&nbsp;</body>' | xmltrip -xhtml
    <?xml version="1.0" encoding="UTF-8"?>
    <body> </body>

I would think that the correct output would be

    <body>&nbsp;</body>

I guess this corresponds to a limitation in Xmlm.output_doc_tree, which has no hook for transforming the output on the way out.

Is there a recommended approach for this?

**Comment by dbuenzli** [comment]
> I'm trying to use xmlm to do transformation some xhtml-like input, and I'm running into an issue. In particular, it doesn't seem possible to handle xhtml entities on both input and output.

It is but you need to resolve them correctly. You will then have in the output the resolved entities rather than entities, but that is correct from a data preservation point of view.

> $ echo '<body>&nbsp;</body>' | xmltrip -xhtml
> <?xml version="1.0" encoding="UTF-8"?>
> <body> </body>

This output is correct: if you pipe this further in `utftrip -a` you will see that this space here is an U+000A which is the resolution of `&nbsp;` entity.

**Comment by dbuenzli** [comment]
So data round trips, but the concrete syntax does not, which is a limitation of xmlm I intended to once lift, but don't hold your breath.
